### ISSUE TITLE
Improve UX and vscode UI

### ISSUE THREAD

**Issue by marcinbodnar** [near/near-vscode#4]
Few problems that we have with the current UX/UI:
1. User needs to type the command to perform many action.
2. If you open a new vscode window (without any project in the workspace) then you are able to click "View NEAR.social account" button and open an account. But after you open an account, it's opened as a workspace, and when you close this workspace than "View NEAR.social account" button is not visible anymore.
3. If you have a vscode window with some project in the workspace, these are no buttons to work with, you need to use the command to view the account or login.
4. When you have an account as a separate workspace, it will be problematic to handle save locally functionality. We would have to make some kind of mix of separate workspaces or add some options to the list of widgets, that will indicate whether it's a local version or not. It might be problematic.

I would propose doing it differently so that it will be easy to work with widgets that are on the chain and locally at the same time. Also some other small changes.

The main change will be that there will be a separate option to the Primary Side Bar (that's how vscode is naming it) that many extensions are using. And closing most of the Near.social functionalities in this option.

1. When you finish near.social extension installation, a new ICON in the Primary Side Bar appears.
2. When you click the icon, the new sidebar will open, and there will be several options available:
 - "View NEAR.social account" - the same options as it is now but always visible
 - "Login and view account" - it will do the same as the command "login" is doing now - always visible
 - List of accounts that you are already loggedin to, with the option to LOGOUT from every account separately
 - The list of all opened accounts and the list of widgets inside the accounts - exactly like it is now. But instead of showing it as a workspace in the vscode EXPLORER, it will be available here. So the user can open a widget, made changes, publish or save locally.

Saving widget locally.
My proposition is to make it work like that:
 - user is opening the widget by clicking on the widget from the list of the widgets on-chain, like he is doing now
 - user made some changes and wants to save it locally (not publish it)
 - the user clicks cmd+s, now the vscode should show the standard options to choose a workspace folder, and after that, the file is saved in this folder
 - now the user can see this file in the vscode EXPLORER, as a workspace.

The main idea here is that we are separating two main things:
 - what is on the chain, and all on-chain actions
 - what the user has locally.

Also, it doesn't matter if the user is working on the local widget file or on-chain widget, he has the options to Publish and Preview available.

If for example, he made a change to the local widget file and clicked Publish, this widget will be published on the chain.

4. Changes to Preview
 - OPTIONAL: it would be good to add a loader, it can take a few seconds to load the preview - the user should see that something is happening, and it's worth wait.
 - if the user is working on a widget file locally he should see the local version of the preview, and it should be refreshed every time he saves
 - if the user is working on the widget on the chain, the preview should show the version from the chain, and when the user publishes the preview should refresh.

5. Additional changes:
 - Show Preview button - it would be nice if this will be a bit more visible option, not only an icon
 - Publish button - it would be nice if this will be a bit more visible option, not only an icon
 - Reload preview button - the same, it's not well visible now.

**Comment by maxhr** [comment]
> 4\. When you have an account as a separate workspace, it will be problematic to handle save locally functionality. We would have to make some kind of mix of separate workspaces or add some options to the list of widgets, that will indicate whether it's a local version or not. It might be problematic.

Yes. There is already a functionality on main branch that tracks local changes, but it uses global-storage for the extension. (btw, it also marks widgets that has been edited in the UI, just like git changes).
I didn't test it yet but probably there will be collisions between separate workspaces with same files, probably just like if you open same file in two editors and try to edit and save in parallel - one might overwrite the other in an unpredictable manner.

 It is possible to use workspace-storage for that to track changes per-workspace.



> I would propose doing it differently so that it will be easy to work with widgets that are on the chain and locally at the same time. Also some other small changes.

I agree, there are many possibilities, it's just a matter of UX decisions - https://code.visualstudio.com/api/ux-guidelines/overview

Ethereum has this full-blown extravaganza - https://marketplace.visualstudio.com/items?itemName=RemixProject.ethereum-remix

Let's see what we can take as inspiration.



> OPTIONAL: it would be good to add a loader, it can take a few seconds to load the preview - the user should see that something is happening, and it's worth wait.

Yes.

> if the user is working on a widget file locally he should see the local version of the preview, and it should be refreshed every time he saves

Debatable. Sometimes widgets are HEAVY as hell. I suggest a toggle for live-reload.

The preview now works with your local changes, and it also supports nested widgets previews. So if you work on two widgets where one includes the other - it'll preview also the inner widget. I actually would like to add a UI indicator for the inner widgets, maybe mark them with a colorful border. Let's discuss this.

>Show Preview button - it would be nice if this will be a bit more visible option, not only an icon
Publish button - it would be nice if this will be a bit more visible option, not only an icon
Reload preview button - the same, it's not well visible now.

Yes, but we are limited with what VSCode provides us to hook into - https://code.visualstudio.com/api/ux-guidelines/overview

Maybe having a tutorial explaining the usage can help - https://code.visualstudio.com/api/ux-guidelines/walkthroughs

BTW, the preview behavior is an exact (or at least tries to be) replica of Markdown files preview behavior.

The publish button should be on a dedicated NEAR panel so that the user can confidently decide what he wants to do, just like pushing to git. Eventually you would probably work on multiple widgets and publish when you finish, so a dedicated panel for you to review your work is a good option.

**Comment by gagdiez** [comment]
Multiple changes have been committed to address these issues.
